apiVersion: v1
kind: Service
metadata:
  name: marketdata-rest-services
spec:
  type: LoadBalancer
  ports:
  - name: "8000"
    port: 8000
    targetPort: 8000
  selector:
    app: marketdata-rest-services
